name: fresh_grpc
description: An grpc link for token refresh. Built on top of package:grpc and manages authentication tokens transparently.
repository: https://github.com/amondnet/fresh_grpc
issue_tracker: https://github.com/amondnet/fresh_grpc
homepage: https://github.com/amondnet/fresh_grpc

version: 0.2.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fresh: ^0.4.0
  grpc: ^3.0.0
  http: ^0.13.3
  meta: ^1.3.0
  pedantic: ^1.11.0
  retry: ^3.1.0
dev_dependencies:
  #test_cov: ^1.0.1
  mocktail: ^0.1.3
  test: ^1.16.0
  very_good_analysis: ^2.1.1
  test_coverage: ^0.5.0
  helloworld:
    path: helloworld

