name: fresh_grpc
description: An grpc link for token refresh. Built on top of package:grpc and manages authentication tokens transparently.
repository: https://github.com/amondnet/fresh_grpc
issue_tracker: https://github.com/amondnet/fresh_grpc
homepage: https://github.com/amondnet/fresh_grpc

version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  fresh: ^0.4.1
  grpc: ^3.2.0
  http: '>=0.13.0 <2.0.0'
  http2: ^2.2.0
  meta: ^1.3.0
  retry: ^3.1.0
dev_dependencies:
  #test_cov: ^1.0.1
  mocktail: ^0.3.0
  test: ^1.16.0
  very_good_analysis: ^5.0.0+1
  helloworld:
    path: helloworld

