name: fresh_grpc

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/fresh_grpc.yaml"
      - "lib/**"
      - "test/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/fresh_grpc.yaml"
      - "lib/**"
      - "test/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.12
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: pub get
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test
      - name: Run tests
        run: pub run test_coverage
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: coverage/lcov.info